language: node_js
node_js:
  - "lts/*"

branches:
  only:
  - master
  - dev
  - feature-travisTest

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "rustaska-github"
    branches:
      - master
      - dev
  chrome: stable

script:
  - webdriver-manager update && webdriver-manager start &
  - sleep 5
  - yarn test
  - sonar-scanner