language: node_js
node_js:
  - "lts/*"

branches:
  only:
  - master
  - dev

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "rustaska-github"
    branches:
      - master
      - dev

script:
  - sonar-scanner